name: bhumi_mitra
description: Land Survey and Measurement App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.12.3
  google_maps_flutter_web: ^0.5.12+2
  geolocator: ^14.0.2
  proj4dart: ^2.1.0
  collection: ^1.18.0
  share_plus: ^7.2.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  # New dependencies for enhanced features
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.1
  printing: ^5.11.0
  permission_handler: ^11.0.1
  location: ^4.4.0
  image: ^4.1.3
  qr_flutter: ^4.1.0
  flutter_cache_manager: ^3.3.1
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_typeahead: ^5.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Mangalvedhe.geojson

